# relu

In [8]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with ReLU activation
    Z1 = np.dot(W1, X) + b1
    A1 = relu(Z1)
    
    # Output layer without softmax activation
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - ReLU):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - ReLU):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

Z2 (Output layer pre-activation):
[[-8.2746529 ]
 [-3.24213524]]


# tanh

In [11]:
import numpy as np

def tanh(x):
    return np.tanh(x)

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with tanh activation
    Z1 = np.dot(W1, X) + b1
    A1 = tanh(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with tanh activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - tanh):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - tanh):
[[0.66568973]
 [0.9788486 ]
 [0.9710057 ]
 [0.70055078]]

Z2 (Output layer pre-activation):
[[-3.78055591]
 [-2.23771772]]


# sigmoid

In [12]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with sigmoid activation
    Z1 = np.dot(W1, X) + b1
    A1 = sigmoid(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with sigmoid activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - sigmoid):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - sigmoid):
[[0.69060784]
 [0.90630086]
 [0.89183275]
 [0.70440877]]

Z2 (Output layer pre-activation):
[[-3.50132496]
 [-2.2193112 ]]


# elu

In [13]:
import numpy as np

def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with ELU activation
    Z1 = np.dot(W1, X) + b1
    A1 = elu(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with ELU activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - ELU):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - ELU):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

Z2 (Output layer pre-activation):
[[-8.2746529 ]
 [-3.24213524]]


# prelu

In [16]:
import numpy as np

def prelu(x, alpha):
    return np.where(x > 0, x, alpha * x)

def forward_propagation(X, W1, b1, W2, b2, alpha):
    # Hidden layer with PReLU activation
    Z1 = np.dot(W1, X) + b1
    A1 = prelu(Z1, alpha)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with PReLU activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Learnable parameter for PReLU
alpha = np.random.rand()

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2, alpha)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - PReLU):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[ 1.26243854]
 [-1.69793816]
 [-1.73697755]
 [-1.81055193]]

A1 (Hidden layer activation - PReLU):
[[ 1.26243854]
 [-0.77437863]
 [-0.79218332]
 [-0.82573839]]

Z2 (Output layer pre-activation):
[[3.61781938]
 [0.36353146]]


# leaky relu

In [18]:
import numpy as np

def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with Leaky ReLU activation
    Z1 = np.dot(W1, X) + b1
    A1 = leaky_relu(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with Leaky ReLU activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - Leaky ReLU):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - Leaky ReLU):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

Z2 (Output layer pre-activation):
[[-8.2746529 ]
 [-3.24213524]]


# selu

In [20]:
import numpy as np

def selu(x, alpha=1.67326, scale=1.0507):
    return scale * np.where(x > 0, x, alpha * (np.exp(x) - 1))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with SELU activation
    Z1 = np.dot(W1, X) + b1
    A1 = selu(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with SELU activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - SELU):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - SELU):
[[0.84367273]
 [2.38433488]
 [2.2165567 ]
 [0.91240823]]

Z2 (Output layer pre-activation):
[[-8.6941778 ]
 [-3.40651149]]


# Softsign

In [22]:
import numpy as np

def softsign(x):
    return x / (1 + np.abs(x))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with Softsign activation
    Z1 = np.dot(W1, X) + b1
    A1 = softsign(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with Softsign activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - Softsign):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - Softsign):
[[0.4453573 ]
 [0.69412247]
 [0.67841523]
 [0.46477734]]

Z2 (Output layer pre-activation):
[[-2.65184017]
 [-1.50536973]]


# softplus

In [24]:
import numpy as np

def softplus(x):
    return np.log(1 + np.exp(x))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with Softplus activation
    Z1 = np.dot(W1, X) + b1
    A1 = softplus(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with Softplus activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - Softplus):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - Softplus):
[[1.17314568]
 [2.36766623]
 [2.22407665]
 [1.21877775]]

Z2 (Output layer pre-activation):
[[-8.76780502]
 [-4.18496513]]


# hard sigmoid

In [26]:
import numpy as np

def hard_sigmoid(x):
    return np.maximum(0, np.minimum(1, 0.2 * x + 0.5))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with Hard Sigmoid activation
    Z1 = np.dot(W1, X) + b1
    A1 = hard_sigmoid(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with Hard Sigmoid activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - Hard Sigmoid):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - Hard Sigmoid):
[[0.66059251]
 [0.95385645]
 [0.92192   ]
 [0.67367626]]

Z2 (Output layer pre-activation):
[[-3.63419225]
 [-2.15788283]]


# swish

In [28]:
import numpy as np

def swish(x, beta=1.0):
    return x * (1 / (1 + np.exp(-beta * x)))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with Swish activation
    Z1 = np.dot(W1, X) + b1
    A1 = swish(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with Swish activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - Swish):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - Swish):
[[0.55453222]
 [2.05665246]
 [1.88141036]
 [0.6116954 ]]

Z2 (Output layer pre-activation):
[[-7.39000362]
 [-2.48761552]]


# mish

In [30]:
import numpy as np

def mish(x):
    return x * np.tanh(np.log(1 + np.exp(x)))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with Mish activation
    Z1 = np.dot(W1, X) + b1
    A1 = mish(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with Mish activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - Mish):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - Mish):
[[0.6626673 ]
 [2.2297826 ]
 [2.0608056 ]
 [0.72882658]]

Z2 (Output layer pre-activation):
[[-8.07038892]
 [-2.8710524 ]]


# Sigrelu= sigmoid + relu

In [33]:
import numpy as np

def sigrelu(x):
    return np.where(x > 0, np.maximum(0, x), 1 / (1 + np.exp(-x)))

def forward_propagation(X, W1, b1, W2, b2):
    # Hidden layer with sigrelu activation
    Z1 = np.dot(W1, X) + b1
    A1 = sigrelu(Z1)
    
    # Output layer without activation (for simplicity)
    Z2 = np.dot(W2, A1) + b2
    
    return Z1, A1, Z2

# Example usage with sigrelu activation:
input_size = 3
hidden_size = 4
output_size = 2

# Random initialization of weights and biases
np.random.seed(42)
W1 = np.random.randn(hidden_size, input_size)
b1 = np.zeros((hidden_size, 1))
W2 = np.random.randn(output_size, hidden_size)
b2 = np.zeros((output_size, 1))

# Dummy input data
X = np.random.randn(input_size, 1)

# Forward propagation
Z1, A1, Z2 = forward_propagation(X, W1, b1, W2, b2)

# Print the results
print("Z1 (Hidden layer pre-activation):")
print(Z1)
print("\nA1 (Hidden layer activation - sigrelu):")
print(A1)
print("\nZ2 (Output layer pre-activation):")
print(Z2)


Z1 (Hidden layer pre-activation):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

A1 (Hidden layer activation - sigrelu):
[[0.80296253]
 [2.26928227]
 [2.10959998]
 [0.8683813 ]]

Z2 (Output layer pre-activation):
[[-8.2746529 ]
 [-3.24213524]]
